### ISSUE TITLE
Apparent error in calculation of driving force

### ISSUE THREAD

**Issue by broshe** [richardotis/pycalphad#22]
Hi Richard,
I installed pycalphad 0.2.1
pycalphad.__version__
'0.2.1'

Now I tried to calculate the driving force for precipitation of the Al13Fe4 phase from liquid Al-Fe at x(Fe)=0.1

Here is the script:

from pycalphad import Database, binplot, equilibrium
import pycalphad.variables as v
from numpy import *
from pylab import *

db = Database('/home/ebrosh/Documents/ebroshWorks/tcworks/Al-Fe-solidification/alfe_sei.TDB')

R=8.31451
T=arange(1000,2001,20)
xAl=.9
xFe=1-xAl
data = equilibrium(db, ['AL', 'FE'], 'LIQUID', {v.X('AL'): xAl, v.T: T, v.P: 1e5},verbose=False)

muFe=data['MU'].sel( component='FE').data[0].flatten()
muAl=data['MU'].sel( component='AL').data[0].flatten()

data = equilibrium(db, ['AL', 'FE','VA'], 'AL13FE4', {v.X('AL'): 13/17.0, v.T: T, v.P: 1e5},verbose=False)
G=data['GM'].data[0].flatten()

dGM=-(G-xAl*muAl-xFe*muFe)/R/T

figure(1)
plot(T,dGM,'g')
![dgm](https://cloud.githubusercontent.com/assets/13480270/9815282/7bfda1a8-589d-11e5-98ef-acfe6258cf55.png)

show(block=False)

The calculation gives positive driving force below 1800 K.
It should be positive below ~1250 K as can be seen on the Al-Fe phase diagram.
A corresponding result of a thermo-calc calculation is also attached (with the correct result).
![dgm_thermocalc](https://cloud.githubusercontent.com/assets/13480270/9815688/aaa78af2-58a0-11e5-9939-1652f10536b8.png)

It seems that the calculation of the Gibbs energy of Al13Fe4  is erroneous in pycalphad

For reference, Gm(Al13Fe4) mu(Al) and mu(Fe) at T=2000 x(Al)=0.9 x(Fe)=.1 are given

pycalphad:
mu(Al)=-130684.44533461
mu(Fe)=-202444.57089581
Gm(Al13Fe4)=-134716.70446316

Thermo-calc:
mu(Al)=-130684.45
mu(Fe)=-202444.6
Gm(Al13Fe4)=-136221.09

Eli

**Comment by richardotis** [comment]
Hi Eli, try changing the dGM line to this. The reason is that driving force must be computed between two states at the same composition. Since your G for AL13FE14 is at X(AL)=13/17, you should choose the same composition for the liquid, even though the liquid potentials are computed at a different composition. Please let me know if you have questions about this.
```python
dGM=-(G-(13/17.0)*muAl-(1-13/17.0)*muFe)/R/T
````
When I do that, I get this plot:
![image](https://cloud.githubusercontent.com/assets/6405510/9817499/50b5cea2-5871-11e5-994f-bae9293206de.png)

That looks visually similar to your Thermo-Calc plot, but please verify numerically. (Not sure why I get the kink in the graph; probably a convergence problem. Please file another bug if it causes you trouble.)

**Comment by broshe** [comment]
Hi Richard,
I think this time the error is mine.
In the calculation of the driving force,
I should have put x(Al)=13/17 x(Fe)=4/17
In my script these were the same as in the liquid.
Sorry. This is my neglect not a bug.
Regards
Eli

**Comment by richardotis** [comment]
No problem! Thanks for the example, I will add it to the documentation for a future release.
